package com.baibao.cloud;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYNERGY_ORDER_ITEM".
 */
public class SynergyOrderItem {

    private Long id;
    private String ddh;
    private String qy;
    private String ddje;
    private Integer jhzt;

    public SynergyOrderItem() {
    }

    public SynergyOrderItem(Long id) {
        this.id = id;
    }

    public SynergyOrderItem(Long id, String ddh, String qy, String ddje, Integer jhzt) {
        this.id = id;
        this.ddh = ddh;
        this.qy = qy;
        this.ddje = ddje;
        this.jhzt = jhzt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDdh() {
        return ddh;
    }

    public void setDdh(String ddh) {
        this.ddh = ddh;
    }

    public String getQy() {
        return qy;
    }

    public void setQy(String qy) {
        this.qy = qy;
    }

    public String getDdje() {
        return ddje;
    }

    public void setDdje(String ddje) {
        this.ddje = ddje;
    }

    public Integer getJhzt() {
        return jhzt;
    }

    public void setJhzt(Integer jhzt) {
        this.jhzt = jhzt;
    }

}
