package com.baibao.cloud;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYNERGY_ORDER_MER_ITEM".
 */
public class SynergyOrderMerItem {

    private Long id;
    private String sku;
    private String qr_code;
    private String wpmc;
    private String item_code;
    private String code;
    private String wpdj;
    private String wpsl;
    private String dw;
    private String address;
    private Boolean status;

    public SynergyOrderMerItem() {
    }

    public SynergyOrderMerItem(Long id) {
        this.id = id;
    }

    public SynergyOrderMerItem(Long id, String sku, String qr_code, String wpmc, String item_code, String code, String wpdj, String wpsl, String dw, String address, Boolean status) {
        this.id = id;
        this.sku = sku;
        this.qr_code = qr_code;
        this.wpmc = wpmc;
        this.item_code = item_code;
        this.code = code;
        this.wpdj = wpdj;
        this.wpsl = wpsl;
        this.dw = dw;
        this.address = address;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getQr_code() {
        return qr_code;
    }

    public void setQr_code(String qr_code) {
        this.qr_code = qr_code;
    }

    public String getWpmc() {
        return wpmc;
    }

    public void setWpmc(String wpmc) {
        this.wpmc = wpmc;
    }

    public String getItem_code() {
        return item_code;
    }

    public void setItem_code(String item_code) {
        this.item_code = item_code;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getWpdj() {
        return wpdj;
    }

    public void setWpdj(String wpdj) {
        this.wpdj = wpdj;
    }

    public String getWpsl() {
        return wpsl;
    }

    public void setWpsl(String wpsl) {
        this.wpsl = wpsl;
    }

    public String getDw() {
        return dw;
    }

    public void setDw(String dw) {
        this.dw = dw;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

}
