package com.baibao.cloud;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.baibao.cloud.bean.SynergyOrderItemInfo;

/**
 * Entity mapped to table "SYNERGY_MER_ITEM".
 */
public class SynergyMerItem {

    private Long id;
    private String sku;
    private String ddh;
    private String wpsl;
    private String address;
    private String pcode;
    private String unit;
    private String price;
    private String name;
    private String number;

    public SynergyMerItem() {
    }

    public SynergyMerItem(Long id) {
        this.id = id;
    }

    public SynergyMerItem(Long id, String sku, String ddh, String wpsl, String address, String pcode, String unit, String price, String name, String number) {
        this.id = id;
        this.sku = sku;
        this.ddh = ddh;
        this.wpsl = wpsl;
        this.address = address;
        this.pcode = pcode;
        this.unit = unit;
        this.price = price;
        this.name = name;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getDdh() {
        return ddh;
    }

    public void setDdh(String ddh) {
        this.ddh = ddh;
    }

    public String getWpsl() {
        return wpsl;
    }

    public void setWpsl(String wpsl) {
        this.wpsl = wpsl;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPcode() {
        return pcode;
    }

    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }


    @Override
    public boolean equals(Object obj_) {
        if(!(obj_ instanceof SynergyOrderItemInfo)){
            return false;
        }
        SynergyMerItem obj = (SynergyMerItem)obj_;
        if (obj.getDdh() != null && obj.getSku() != null) {
            if (obj.getDdh() == getDdh() && obj.getSku() == getSku()) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }

    @Override
    public int hashCode() {
        String id_str = getDdh() + getSku();
        int ids = id_str.hashCode();
        return ids;
    }
}
